### ISSUE TITLE
Error during formatting of disk "Bad block count" followed by "Usage: mkfs.fat..."

### ISSUE THREAD

**Issue by LuRsT** [ChimeraOS/install-media#24] opened 2020-10-11 18:36 UTC
It doesn't look like I actually have an issue with bad blocks on my disk because `fdisk` tells me it's all OK. The error of bad usage may be the culprit, but I couldn't figure out where that command `mkfs.fat` is happening on `install.sh`.

I'm trying to install it in a single ssd.

**Comment by 80Proof** [comment] 2021-02-19 00:38
same issue here. trying to install on a surface pro 3. flashed with rufus, in DD mode, cuz ISO kept crashing too.

**Comment by BluePR0** [comment] 2021-03-28 21:18
Same issue here. Did anyone find an answer?

**Comment by sowbug** [comment] 2021-06-06 07:16
I came close to a horrible hack to work around this for my individual installation. I'm hoping to submit a patch to fix it properly, or maybe to provide enough of a root cause for @alkazar to quickly fix it. The problem isn't in this project, but rather in the `gamer-os/frzr` project that's a peer to this one.

All these device paths are what I saw on my device (a Chuwi Larkbox). Yours will vary, and they're certainly different from what @alkazar has. Use your judgment. And be aware that you're juggling with chainsaws -- get these mods wrong, and you initialize the wrong disk or partition.

The problem is that your installation craps out with that "Bad block count" message dumping you out to the console. It's actually happening because a command generated by the script `/usr/bin/frzr-bootstrap` is being sent that's supposed to look like this: `mkfs.vfat /dev/mmcblk0p1` but it actually looks like this: `mkfs.vfat /dev/mmcblk0boot1 /dev/mmcblk0p1`. The tool mkfs interprets `/dev/mmcblk0p1` as the desired block count of your new partition, which doesn't make sense.

The root cause is that the argument sent to mkfs.vfat is malformed. ${PART1} is assigned from the expression `PART1=$(ls ${DISK}* | grep "${DISK}.*1$")` (https://github.com/gamer-os/frzr/blob/master/frzr-bootstrap#L54). But because your ls ${DISK} looks like this:

/dev/mmcblk0
/dev/mmcblk0boot0
/dev/mmcblk0boot1
/dev/mmcblk0p1
/dev/mmcblk0p2
/dev/mmcblk0rpmb

that expression ends up picking up both `/dev/mmcblk0boot1` and `/dev/mmcblk0p1` when it was probably supposed to result only in `/dev/mmcblk0p1`.

@alkazar I bet you're the only person on Earth who understands what I'm trying to say (I know I only barely do), and I'm sure you have a real fix in mind. I'm not sure how to reliably distinguish the boot1 device from the p1 device using the grep method you're using. I could imagine other devices coming up with other naming schemas, so we can't rely on alphabetical ordering.

*Anyway*, my quick fix for my own installation was this:

- See the error
- Get dumped out to console
- `ls -l /dev/mmcblk0*` and, as a human rather than a script, figure out what partition 1 and 2 are.
- `nano /usr/bin/frzr-bootstrap`
- edit line 54 to read `PART1=/dev/mmcblk0p1` (this is what I decided the right value is after looking at the `ls` output) 
- edit line 55 to read `PART2=/dev/mmcblk0p2` (same)
- save and exit nano
- `umount /dev/mmc*` (this is needed to unmount the half-created disk partitions from the prior failure)
- control-D and run through setup again with the hacked bootstrap script

I'm still going through the rest of the setup as I type up this diagnosis, so I don't yet know whether it worked. But this might help someone else succeed even if I don't.

**Comment by alkazar** [comment] 2021-06-06 15:26
@sowbug thanks for the details. I suppose we could drop anything with "boot" or "rpmb" in it, but I wonder if there is a more direct way to obtain a list of actual usable partitions.

**Comment by sowbug** [comment] 2021-06-06 15:41
`parted` has a `-m` option to output in a machine-readable format, so `parted -s -l -m` or `parted -s -m ${DISK} print` look like candidates. I have LVM on my Linux workstation, so my own test output is weird, but I think it could work more predictably. Perhaps you could even set specific partition names earlier in the partition-creation part of the script using `parted`'s `name` command, and then you can uniquely identify them later when you're asking `parted` for the device name corresponding to the partition you just created.

**Comment by alkazar** [comment] 2021-06-06 15:57
@sowbug could you also check what `fdisk --list ${DISK}` looks like while you are at it?

**Comment by sowbug** [comment] 2021-06-06 16:03
Yes, both `lsblk -l -p ${DISK}` and `fdisk --list ${DISK}` output includes just the desired partitions and not the garbage device names. So assuming `lsblk` is available on your archlinux-based system (and I'm sure it is), it's just a question of which is easier to parse.

From my Linux workstation on a spare USB disk:

lsblk:

```
$ lsblk -l -p /dev/sda
NAME      MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
/dev/sda    8:0    1 14.4G  0 disk 
/dev/sda1   8:1    1  511M  0 part 
/dev/sda2   8:2    1 13.9G  0 part 
```

fdisk:

```
$ sudo fdisk --list /dev/sda
Disk /dev/sda: 14.42 GiB, 15472047104 bytes, 30218842 sectors
Disk model: DataTraveler 3.0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xe83c9560

Device     Boot   Start      End  Sectors  Size Id Type
/dev/sda1          2048  1048575  1046528  511M  c W95 FAT32 (LBA)
/dev/sda2       1048576 30218239 29169664 13.9G 83 Linux
```

I'll fiddle with `fdisk` params to make it easier to parse.

**Comment by sowbug** [comment] 2021-06-06 16:09
The best I could find from `--help` and `man` is `-o Device`, which gives us this:

```
$ sudo fdisk -o Device --list /dev/sda
Disk /dev/sda: 14.42 GiB, 15472047104 bytes, 30218842 sectors
Disk model: DataTraveler 3.0
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xe83c9560

Device
/dev/sda1
/dev/sda2
```

This feels ugly because I don't trust the header output to change in a year or two and mess things up, but I guess you could pipe it through grep:

```
$ sudo fdisk -o Device --list /dev/sda | grep "^${DISK}"
/dev/sda1
/dev/sda2
```

**Comment by alkazar** [comment] 2021-06-06 17:39
Thanks! Should be fixed in https://github.com/gamer-os/frzr/commit/59aa830572495330844db30f8408cad94ffa3b28

I only tested it in a VM though.

I will release new install media soon.

**Comment by sowbug** [comment] 2021-06-06 17:47
If you comment on this issue when a new installer is ready, I'm willing to verify the fix.

I don't know whether it's exactly the same issue that the other commenters encountered because they didn't include the device path that was mucking things up in their comments, but it seems likely it is. @LuRsT @80Proof @BluePR0, if any of you are still interested in trying GamerOS, please wait for the new installer with this fix and try again.

**Comment by alkazar** [comment] 2021-06-23 02:46
Hi, I have published new install media with a fix for this issue. Any help testing would be appreciated!

**Comment by alkazar** [comment] 2021-08-21 21:26
I believe this issue is fixed now. Feel free to re-open if it comes back.

**Closed by alkazar** 2021-08-21 21:26 UTC
